### ISSUE TITLE
Clarification on thingName and ClientID

### ISSUE THREAD

**Issue by srini-murthy** [mariocannistra/python-paho-mqtt-for-aws-iot#2]
Dear Author,

You are using thingName which is the name of a Thing and ClientID 
How are these two variables:

clientId = "myThingName"
thingName = "myThingName"

used in awsiotsub.py and awsiotpub.py 

Please clarify,

With Thanks and Regards
Srini

**Comment by mariocannistra** [comment]
Hello Srini.
Those 2 variables ( clientId and thingName ) are not used here and you can delete those 2 lines, the examples will still work fine.  If you want to distinguish data being sent from different IoT devices you can easily set the messages "topic" that work in a "tree like" way.  Good documentation here:   [http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180919](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/errata01/os/mqtt-v3.1.1-errata01-os-complete.html#_Toc442180919)

I wrote these example programs when working at my radio-astronomy project  [https://www.hackster.io/mariocannistra/radio-astronomy-with-rtl-sdr-raspberrypi-and-amazon-aws-iot-45b617](https://www.hackster.io/mariocannistra/radio-astronomy-with-rtl-sdr-raspberrypi-and-amazon-aws-iot-45b617)  

In next version of that project I will probably use those two variables to identify different receiving stations sending data using MQTT on Raspberry PI.

Kind regards,
Mario

**Comment by srini-murthy** [comment]
Dear Mario,

Thanks for the reply,  Yes, understood  

My need is to send the messages to thing shadow - if you can show me how to pass these two variables in API will be great and sincerely appreciated

Regards,
Srini

**Comment by srini-murthy** [comment]
Dear Mario,

By the way your Astronomy project  is Very Very Cool and I wish you all the best 

Best,
Srini

**Comment by mariocannistra** [comment]
Thank you Srini. I hope to publish version 2 soon.

To update the state of a thing shadow you must send a properly formatted json message and in this case use the proper thing name.
To try this you can delete this line:

`mqttc.publish("temperature", tempreading, qos=1)`

and replace it with:

```
        jsonMessage = "{ \"state\": { \"reported\": { \"temperature\": " + str(tempreading) + "} } }"
        mqttc.publish("$aws/things/**myThingName**/shadow/update", jsonMessage, qos=1)
```

In this way you will update the state of the shadow for the thing named "**myThingName**".  Obviously you have to use here the name that you used when creating the thing, certificates, etc like explained in my instructions.

You can check the shadow state on the AWS IoT dashboard.  Selecting the thing and looking at the right side panel you will see something like:
![image](https://cloud.githubusercontent.com/assets/1177953/13703307/5d77d0be-e795-11e5-8276-b8e0afa5fc11.png)

Some useful docs:

http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html

http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-document.html#thing-shadow-example

http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-document-syntax.html

Ciao,
Mario

**Comment by srini-murthy** [comment]
Thank you very much Mario, 

Greatly appreciated !

Best Regards,
Srini
