### ISSUE TITLE
Problem with subscription

### ISSUE THREAD

**Issue by Piero87** [mariocannistra/python-paho-mqtt-for-aws-iot#3]
Hi Mario,
Thank you very much to share this code, I'm trying to use it with a little modification but I have a problem, this is my code:

publish:

```
#!/usr/bin/python3

#required libraries
import sys                                 
import ssl
import paho.mqtt.client as mutt
from time import sleep
from random import uniform

connflag = False

def on_connect(client, userdata, flags, rc):
    global connflag
    connflag = True
    print("Connection returned result: " + str(rc) )

def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))
    print("Received message from topic: "+msg.topic+" | QoS: "+str(msg.qos)+" | Data Received: "+str(msg.payload))

mqttc = mqtt.Client(client_id="RaspberryPi_2", clean_session=True)

mqttc.on_connect = on_connect
mqttc.on_message = on_message


mqttc.tls_set("/home/pi/aws_iot/things/raspberryPi_2/certs/aws-iot-rootCA.crt",
                certfile="/home/pi/aws_iot/things/raspberryPi_2/certs/0ea2cd7eb6-certificate.pem.crt",
                keyfile="/home/pi/aws_iot/things/raspberryPi_2/certs/0ea2cd7eb6-private.pem.key",
              tls_version=ssl.PROTOCOL_TLSv1_2,
              ciphers=None)

mqttc.connect("A2GF7W5U5A46J1.iot.us-west-2.amazonaws.com", port=8883)

mqttc.loop_start()

while 1==1:
    sleep(0.5)
    if connflag == True:
        tempreading = uniform(20.0,25.0)
        #jsonMessage = "{ \"state\": { \"reported\": { \"temperature\": " + str(tempreading) + "} } }"
        #mqttc.publish("$aws/things/RaspberryPi_2/shadow/update", jsonMessage, qos=1)
        mqttc.publish("topic/test",tempreading,qos=1)
        print("msg sent: temperature " + "%.2f" % temp reading )
    else:
        print("waiting for connection...")
```

subscription:

```
#!/usr/bin/python3

#required libraries
import sys                                 
import ssl
import paho.mqtt.client as mqtt
import RPi.GPIO as gpio
from time import sleep

try:
    ledPin = 25
    gpio.setmode(gpio.BCM)
    gpio.setup(ledPin, gpio.OUT)

    def on_connect(client, userdata, flags, rc):
        print("Connected with result code "+str(rc))
        client.subscribe("topic/test",1)

    def on_message(client, userdata, msg):
        print("Message received: "+str(msg.payload))

        if str(msg.payload) >= '23':
            print("High Temperature")
            print(str(msg.payload))
            GPIO.output(ledPin, GPIO.HIGH)
            time.sleep(.1)
            GPIO.output(ledPin, GPIO.LOW)


    def on_subscribe(mqttc, obj, mid, granted_qos):
        print("Subscribed: "+str(mid)+" "+str(granted_qos)+"data"+str(obj))


    mqttc = mqtt.Client(client_id="RaspberryPi_2", clean_session=True)

    mqttc.on_connect = on_connect
    mqttc.on_message = on_message
    mqttc.on_subscribe = on_subscribe


    mqttc.tls_set("/home/pi/aws_iot/things/raspberryPi_2/certs/aws-iot-rootCA.crt",
                    certfile="/home/pi/aws_iot/things/raspberryPi_2/certs/0ea2cd7eb6-certificate.pem.crt",
                    keyfile="/home/pi/aws_iot/things/raspberryPi_2/certs/0ea2cd7eb6-private.pem.key",
                  tls_version=ssl.PROTOCOL_TLSv1_2,
                  ciphers=None)

    mqttc.connect("A2GF7W5U5A46J1.iot.us-west-2.amazonaws.com", port=8883) #AWS IoT service hostname and portno

    mqttc.loop_forever()

except KeyboardInterrupt:
    pass
finally:
    gpio.cleanup()
```

This is the log of the publisher:

```
waiting for connection...
Connection returned result: 0
msg sent: temperature 20.68
msg sent: temperature 21.28
msg sent: temperature 23.76
...
msg sent: temperature 24.66
msg sent: temperature 22.92
msg sent: temperature 21.52
msg sent: temperature 20.25
Connection returned result: 0
msg sent: temperature 20.25
msg sent: temperature 20.50
msg sent: temperature 23.31
msg sent: temperature 20.85
...
msg sent: temperature 21.89
msg sent: temperature 21.97
```

This is the log of the subscriber:

```
Connected with result code 0
Subscribed: 1 (1,)dataNone
Connected with result code 0
Subscribed: 2 (1,)dataNone
Connected with result code 0
Subscribed: 3 (1,)dataNone
Connected with result code 0
Subscribed: 4 (1,)dataNone
Connected with result code 0
Subscribed: 5 (1,)dataNone
```

So as you can see there is no print of the `on_message` function, following your solution on the only issue in this project and i have tried this:

```
jsonMessage = "{ \"state\": { \"reported\": { \"temperature\": " + str(tempreading) + "} } }"
mqttc.publish("$aws/things/RaspberryPi_2/shadow/update", jsonMessage, qos=1)
```

and the Thing Shadow on AWS IoT is update, so I think that the connection with AWS is established, can you help me?

I noticed another thing if it can be useful to help me, if I run only the subscriber without the publisher this is the log:

```
Connected with result code 0
Subscribed: 1 (1,)dataNone
```

only one subscription, so it seems that something happens when I start to publish, but it does not work, I hope you can help me thanks

**Comment by mariocannistra** [comment]
Hello Piero.
I cannot try your code until this evening but I noticed a couple of things: connections are continuously dropped because you are using the same client_id="RaspberryPi_2" in both programs.  If you want to specify a clientid for some reason, then you should have them different. Something like "RpiSender" and "RpiReceiver". Another option is to leave it unspecified like I did in my sample: in that way a random one will be generated.

I've seen also that parameter cert_reqs=ssl.CERT_REQUIRED  is missing in the tls_set() statement. Just in case the clientid fix is not enough, try adding back this param as well. But I think that diversifying the clientids should be enough.

Let me know if you got it working. 
One last thing: in my sample I just printed the msg payload binary as a string. If you want to send and manage more data values you should consider parsing the received message with the json module for python (import json).

Cheers,
Mario

**Comment by Piero87** [comment]
Thank you very very much Mario :)
It worked just changing the client id, to clarify I have also add the cert_reqs thank you for the hint :)
Now i'm trying to use json like you suggest, i have do this in the pub:

```
json_data = {'temperature': temp reading }

mqttc.publish("topic/test",json.dumps(json_data),qos=1)
```

and this in the sub:

```
def on_message(client, userdata, msg):
        print("Message received: "+str(msg.payload))

        parsed_json = json.loads(msg.payload)

        if parsed_json['temperature'] >= 23:
            print("High Temperature")
            print(str(msg.payload))
            gpio.output(ledPin, gpio.HIGH)
            sleep(.1)
            gpio.output(ledPin, gpio.LOW)
```

but i get this error for the sub:

```
Connected with result code 0
Subscribed: 1 (1,)dataNone
Message received: b'{"temperature": 20.21611852952066}'
....
File "sub_test.py", line 24, in on_message
    parsed_json = json.loads(msg.payload)
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

I can't understand why give me this error, and what is that "b" character before all the pyload message.
You know what can be the problem?

Thanks again :)

**Comment by Piero87** [comment]
I have solved the problem :)

This is the code for anyone need it:

pub:

```
    payload = {'temperature': tempreading}
    data_string = json.dumps(payload)

    mqttc.publish("topic/test",data_string,qos=1)
```

sub:

```
def on_message(client, userdata, msg):

    json_data = msg.payload.decode('utf-8')

    print("Message received: "+json_data)

    parsed_json = json.loads(json_data)

    if parsed_json["temperature"] > 23:
        gpio.output(ledPin, gpio.HIGH)
        sleep(.1)
        gpio.output(ledPin, gpio.LOW)
```

**Comment by mariocannistra** [comment]
Hi Piero.
Happy you found it. Messages are in binary format and I saw somebody using those to send webcam shots when  movements are detected :-)

To send more variables you can simply do:

Mydata = {}
Mydata["temperature"] = 23
Mydata["pressure"] = 900

And then encode this dictionary as json string and send...

Special json is needed instead if you need to use aws shadow  .

Mario
Sorry for delayed answers... daytime = busy on the job :-)

-----Original Message-----

**Comment by Piero87** [comment]
Thank you very much! :) don't worry for the delay! :)

**Comment by arpitrohela** [comment]
Hello,
I am trying to connect RPi 3 to AWS IoT using MQTT clinet. I tried doing so with your code.
But I am facing issue with connection. Below is my code and the corresponding output.
Can you please help out of this.
`#!/usr/bin/python3

#required libraries
import sys                                 
import ssl
import paho.mqtt.client as mqtt
from time import sleep
from random import uniform

connflag = False

def on_connect(client, userdata, flags, rc):
    global connflag
    connflag = True
    print("Connection returned result: " + str(rc))

def on_message(client, userdata, msg):
    print(msg.topic+" "+str(msg.payload))
    print("Received message from topic: "+msg.topic+" | QoS: "+str(msg.qos)+" | Data Received: "+str(msg.payload))

mqttc = mqtt.Client(client_id="CaptureRFIDData", clean_session=True)

mqttc.on_connect = on_connect
mqttc.on_message = on_message


mqttc.tls_set("/home/pi/AWS IoT/certificates_Capture/rootCA.crt",
                certfile="/home/pi/AWS IoT/certificates_Capture/df5f2c3ae8-certificate.pem.crt",
                keyfile="/home/pi/AWS IoT/certificates_Capture/df5f2c3ae8-private.pem.key",
                cert_reqs=ssl.CERT_REQUIRED,
                tls_version=ssl.PROTOCOL_TLSv1_2,
                ciphers=None)

mqttc.connect("a1hdhui1ajdqbv.iot.us-west-2.amazonaws.com", port=8883)

mqttc.loop_start()

while 1==1:
    sleep(0.5)
    if connflag == True:
        tempreading = uniform(20.0,25.0)
        #jsonMessage = "{ \"state\": { \"reported\": { \"temperature\": " + str(tempreading) + "} } }"
        #mqttc.publish("$aws/things/RaspberryPi_2/shadow/update", jsonMessage, qos=1)
        mqttc.publish("CaptureSensorDataPolicy/test",tempreading,qos=1)
        print("msg sent: temperature " + "%.2f" % tempreading )
    else:
        print("waiting for connection...")
`

The output is as follows:
`waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...
waiting for connection...`

Any help will be appreciated.
Thanking you.

**Comment by mariocannistra** [comment]
Hello. Please try replacing  "a1hdhui1ajdqbv.iot.us-west-2.amazonaws.com"   with "data.iot.us-west-2.amazonaws.com"

**Comment by arpitrohela** [comment]
Thank you Sir for your kind help.
Still I am getting the same output.

`mqttc.connect("data.iot.us-west-2.amazonaws.com", port=8883)`

output:
`waiting for connection... waiting for connection... waiting for connection... waiting for connection... waiting for connection... waiting for connection...
`

**Comment by mariocannistra** [comment]
I'm currently traveling. I will try to reproduce your issue when possible and update here.

**Comment by arpitrohela** [comment]
Ok, Sure.
Thank you for consideration.

**Comment by mariocannistra** [comment]
Hello arpiy.
yesterday evening I tried replicating your missing connection case but the program actually worked well.
I just copied your source, added the indentation that was stripped away by the comments editor, changed the certificates paths to my ones and edited the connection URL to my one.
This is the output:
![image](https://cloud.githubusercontent.com/assets/1177953/24094414/df74fdb4-0d58-11e7-8c00-8ff3366ef647.png)

I think you could check both the .connect() URL and the indentation in your source (some wrong logic resulting in the if connflag == True:  statement ?).

Unfortunately I don't have other suggestions since it just runs fine with my certificates and URL...

cheers,
mario

**Comment by arpitrohela** [comment]
thank you.

**Comment by DataDirk** [comment]
Hi arpiy. I'm having the similar issues executing MQTT paho. I also keep getting "Waiting to connect... Waiting to connect...". Did you ever resolve the issue?
